### 영벡터

- 원소가 모두 0인 벡터(행렬)
- `np.zeros(dim)`을 통해 생성, dim은 값, 혹은 튜플(,)


In [1]:
import numpy as np

In [2]:
np.zeros(3)

array([0., 0., 0.])

In [4]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### 일벡터(행렬)
* 원소가 모두 1인 벡터(행렬)
* `np.ones(dim)` 을 통해 생성

In [6]:
np.ones(2)

array([1., 1.])

In [7]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 대각행렬(diagonal matrix)
* Main diagonal을 제외한 성분이 0인 행렬<br>
ex)[0,0], [1,1], [2,2] 대각선 축을 중심으로 그외는 전부 값이 0임

* `np.diag(main_diagonal)`을 통해 생성

In [10]:
np.diag((2,4))


array([[2, 0],
       [0, 4]])

In [12]:
np.diag((1,3,5))

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

### 항등 행렬(identity matrix)
* Main diagonal이 1인 대각행렬
* `np.eye()` 를 사용 
* 원소의 데이터 타입을 지정해줄수도 있음

In [13]:
np.eye(2,dtype =int)

array([[1, 0],
       [0, 1]])

In [15]:
np.eye(3,dtype = float)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 행렬곱(dot product)
행렬간의 곱연산
* `np.dot() or @ `을 사용

In [18]:
mat_1 = np.array([[1,4],[2,3]])
mat_2 = np.array([[7,9],[0,6]])
mat_1.dot(mat_2)

array([[ 7, 33],
       [14, 36]])

In [19]:
mat_1 @ mat_2

array([[ 7, 33],
       [14, 36]])

### 트레이스(trace)
* Main diagonal의 합
* `np.trace()` 를 사용

In [21]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
arr.trace() # 1 + 5 + 9

15

In [28]:
np.eye(2,dtype =int).trace()

2

### 행렬식(determinant)
* 행렬을 대표하는 값들 중 하나 -> 선형변환
* `np.linalg.det()`으로 계산
*  선형변환 과정에서 Vector의 Saclling 척도

In [31]:
arr_2 = np.array([[2,3],[1,6]])
arr_2

array([[2, 3],
       [1, 6]])

In [33]:
np.linalg.det(arr_2)

9.000000000000002

In [35]:
arr_3 = np.array([[1,4,7],[2,5,8],[3,6,9]])
arr_3

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [36]:
np.linalg.det(arr_3)

0.0

### 역행렬
* 행렬 A에 대해 AB = BA = I를 만족하는 행렬 B = A^-1
* `np.linalg.inv()`으로 계산

In [37]:
mat = np.array([[1,4],[2,3]])
mat

array([[1, 4],
       [2, 3]])

In [39]:
mat_inv = np.linalg.inv(mat)
mat_inv

array([[-0.6,  0.8],
       [ 0.4, -0.2]])

In [41]:
mat.dot(mat_inv)

array([[ 1.00000000e+00,  0.00000000e+00],
       [-1.11022302e-16,  1.00000000e+00]])

### 고유값과 고유 백터

* 정방행렬 (nxn) A에 대해서  $Ax  = \lambda x$ 을 만족하는 $\lambda$와 x를 각각 고유값과 고유벡터라 한다.
* `np.linalg.eig()` 로 계산
* 나온 값들을 column을 기준으로 본다.

In [43]:
mat = np.array([[2,0,-2],[1,1,-2],[0,0,1]])
mat

array([[ 2,  0, -2],
       [ 1,  1, -2],
       [ 0,  0,  1]])

In [44]:
np.linalg.eig(mat)

(array([1., 2., 1.]),
 array([[0.        , 0.70710678, 0.89442719],
        [1.        , 0.70710678, 0.        ],
        [0.        , 0.        , 0.4472136 ]]))

### Validation

In [48]:
eig_val, eig_vec = np.linalg.eig(mat)
eig_val

array([1., 2., 1.])

In [50]:
eig_vec

array([[0.        , 0.70710678, 0.89442719],
       [1.        , 0.70710678, 0.        ],
       [0.        , 0.        , 0.4472136 ]])

In [53]:
mat @ eig_vec[:,0]

array([0., 1., 0.])

eig_val[0] * eig_vec[:,0] # (lambda)x