In [1]:
import numpy as np

### Numpy로 연산하기

### Vector와 Saclar 사이의 연산

벡터의 각 원소에 대해서 연산을 진행
$$ x = \left( \begin{matrix} 1\\ 2\\ 3 \end{matrix} \right) \quad c = 5  $$

In [4]:
x = np.array([1,2,3])
c = 5

print("더하기 : {}".format(x + c))
print("빼기 : {}".format(x - c))
print("곱하기 : {}".format(x * c))
print("나누기 : {}".format(x / c))

더하기 : [6 7 8]
빼기 : [-4 -3 -2]
곱하기 : [ 5 10 15]
나누기 : [0.2 0.4 0.6]


### Vector와 Vector사이의 연산

벡터의 **같은 인덱스**끼리 연산이 진행!!

$$ y = \left( \begin{matrix} 1\\ 3\\ 5 \end{matrix} \right) \quad z = \left( \begin{matrix} 2\\ 9 \\20 \end{matrix} \right) $$


In [12]:
y = np.array([1,3,5])
z = np.array([2,9,20])
print("더하기 : {}".format(y + z))
print("빼기 : {}".format(y - z))
print("곱하기 : {}".format(y * z))
print("나누기 : {}".format(y / z))

더하기 : [ 3 12 25]
빼기 : [ -1  -6 -15]
곱하기 : [  2  27 100]
나누기 : [0.5        0.33333333 0.25      ]


### Array의 Indexing 
Array에서 특정 위치를 원하는 원소를 가지고 오고 싶다면?

$$ W = \left(\begin{matrix} 1 & 2 & 3 & 4 \\ 5 &6 & 7 & 8 \\ 9 & 10 & 11 & 12 \end{matrix} \right)$$

2차원의 기준으로 했을 때 array indexing은 [(row),(column)]으로 들어간다

In [25]:
W = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(W[0,0]) # 1
print(W[2,3]) # 12

1
12


In [28]:
# 7을 가져오려면
W[1,2]


7

### Array의 Slicing
Array에서 특정 범위의 원하는 원소를 가지고 오고 싶다면?
python의 list와 유사하게 진행

In [ ]:
W = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [37]:
W[0:2,1:3]

array([[2, 3],
       [6, 7]])

In [40]:
W[0:2,:] #W[0:2,0:4]와 같음

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### Array의 Broadcasting
Numpy가 연산을 진행하는 특수한 방법!

기본적으로 같은 Type의 data에 대해서만 연산이 적용 가능
하지만 만약에 피연산자가 연산 가능하도록 변환이 가능하다면 연산이 가능합니다.
이를 **Broadcasting** 이라고 합니다.
#### 1. M by N, M by 1

In [47]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
x = np.array([0,1,0])
x = x[:,None] # x 전치
print(x)
print(a+x)

[[0]
 [1]
 [0]]
[[1 2 3]
 [5 6 7]
 [7 8 9]]


#### 2. M by N, 1 by N

In [49]:
y = np.array([0,1,-1])

print([a*y])

[array([[ 0,  2, -3],
       [ 0,  5, -6],
       [ 0,  8, -9]])]


#### 3. M by 1, 1 by N


In [56]:
t = np.array([1,2,3]) # 열벡터로 바꿔줘야함
t = t[:,None] # Transpose
u = np.array([2,0,-2])

print(t+u)

[[ 3  1 -1]
 [ 4  2  0]
 [ 5  3  1]]
